// <auto-generated />
using System;
using EEGGaming.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EEGGaming.Core.Migrations
{
    [DbContext(typeof(EEGGamingDbContext))]
    [Migration("20240526192812_initail creation")]
    partial class initailcreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("EEGGaming.Core.Data.Models.BrainwavesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Alpha1")
                        .HasColumnType("REAL");

                    b.Property<double>("Alpha1_Rel")
                        .HasColumnType("REAL");

                    b.Property<double>("Beta1")
                        .HasColumnType("REAL");

                    b.Property<double>("Beta1_Rel")
                        .HasColumnType("REAL");

                    b.Property<bool>("Blinked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Delta")
                        .HasColumnType("REAL");

                    b.Property<double>("Delta_Rel")
                        .HasColumnType("REAL");

                    b.Property<int>("GamingSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Gamma1")
                        .HasColumnType("REAL");

                    b.Property<double>("Gamma1_Rel")
                        .HasColumnType("REAL");

                    b.Property<byte>("Marker")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MiliSecond")
                        .HasColumnType("REAL");

                    b.Property<uint>("PackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Second")
                        .HasColumnType("REAL");

                    b.Property<double>("Theta")
                        .HasColumnType("REAL");

                    b.Property<double>("Theta_Rel")
                        .HasColumnType("REAL");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BrainWaves");
                });

            modelBuilder.Entity("EEGGaming.Core.Data.Models.GamingSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("User")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameSession");
                });

            modelBuilder.Entity("EEGGaming.Core.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
