.TH "EEGGaming.Trainer/obj/x64/Debug/net8.0-windows7.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Trainer/obj/x64/Debug/net8.0-windows7.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
