.TH "EEGGaming.Core/Migrations/20240616172542_unmade the name property a key.Designer.cs" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core/Migrations/20240616172542_unmade the name property a key.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEEGGaming\&.Core\&.Migrations\&.unmadethenamepropertyakey\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEEGGaming\fP"
.br
.ti -1c
.RI "namespace \fBEEGGaming\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBEEGGaming\&.Core\&.Migrations\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
