.TH "About" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
About \- This is the window that shows the info about the app\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Node2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.RI "Executes when the node isready andfills the info in the window\&. "
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the window that shows the info about the app\&. 
.PP
Definition at line \fB8\fP of file \fBAbout\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void About\&._Process (double delta)"

.PP
Definition at line \fB42\fP of file \fBAbout\&.cs\fP\&.
.SS "override void About\&._Ready ()"

.PP
Executes when the node isready andfills the info in the window\&. 
.PP
Definition at line \fB13\fP of file \fBAbout\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
