.TH "EEGGaming.Core/Managers/AppSettingsManager.cs" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core/Managers/AppSettingsManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEEGGaming\&.Core\&.Managers\&.AppSettingsManager\fP"
.br
.RI "This classmanages the settings of the library\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEEGGaming\fP"
.br
.ti -1c
.RI "namespace \fBEEGGaming\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBEEGGaming\&.Core\&.Managers\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBConfigurationBuilder\fP = Microsoft\&.Extensions\&.Configuration\&.ConfigurationBuilder"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBConfigurationBuilder\fP = Microsoft\&.Extensions\&.Configuration\&.ConfigurationBuilder"

.PP
Definition at line \fB10\fP of file \fBAppSettingsManager\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
