.TH "Camera" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera
.SH SYNOPSIS
.br
.PP
.PP
Inherits Camera2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBCamera\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Camera\&._Process (double delta)"

.PP
Definition at line \fB22\fP of file \fBCamera\&.cs\fP\&.
.SS "override void Camera\&._Ready ()"

.PP
Definition at line \fB9\fP of file \fBCamera\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
