.TH "EEGGaming.Core/obj/Debug Directory Reference" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core/obj/Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBnet6\&.0\fP"
.br
.ti -1c
.RI "directory \fBnet8\&.0\fP"
.br
.in -1c
