.TH "EEGGaming.Trainer.frmMainGUI" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Trainer.frmMainGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfrmMainGUI\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBfrmMainGUI\&.Designer\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EEGGaming\&.Trainer\&.frmMainGUI\&.frmMainGUI ()"

.PP
Definition at line \fB29\fP of file \fBfrmMainGUI\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void EEGGaming\&.Trainer\&.frmMainGUI\&.Dispose (bool disposing)\fR [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB14\fP of file \fBfrmMainGUI\&.Designer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
