.TH "EEGGaming.Core.Data.Models.GamingSesion" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Data.Models.GamingSesion \- The class representation of the Gamingsession table from the database\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEEGGaming\&.Core\&.Data\&.NonDataModels\&.GmingSessionViewModel\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fR [get, set]\fP"
.br
.RI "An auto-incremented value id\&. "
.ti -1c
.RI "DateTime \fBStart\fP\fR [get, set]\fP"
.br
.RI "The time and date the gaming session start\&. "
.ti -1c
.RI "DateTime \fBEnd\fP\fR [get, set]\fP"
.br
.RI "The time and date the gaming session end\&. "
.ti -1c
.RI "int \fBUser\fP\fR [get, set]\fP"
.br
.RI "The user'sid that plays in the current session\&. "
.ti -1c
.RI "double \fBScore\fP\fR [get, set]\fP"
.br
.RI "The score the user scored in this gaming session\&. "
.in -1c
.SH "Detailed Description"
.PP 
The class representation of the Gamingsession table from the database\&. 
.PP
Definition at line \fB15\fP of file \fBGamingSesion\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "DateTime EEGGaming\&.Core\&.Data\&.Models\&.GamingSesion\&.End\fR [get]\fP, \fR [set]\fP"

.PP
The time and date the gaming session end\&. 
.PP
Definition at line \fB32\fP of file \fBGamingSesion\&.cs\fP\&.
.SS "int EEGGaming\&.Core\&.Data\&.Models\&.GamingSesion\&.Id\fR [get]\fP, \fR [set]\fP"

.PP
An auto-incremented value id\&. 
.PP
Definition at line \fB22\fP of file \fBGamingSesion\&.cs\fP\&.
.SS "double EEGGaming\&.Core\&.Data\&.Models\&.GamingSesion\&.Score\fR [get]\fP, \fR [set]\fP"

.PP
The score the user scored in this gaming session\&. 
.PP
Definition at line \fB43\fP of file \fBGamingSesion\&.cs\fP\&.
.SS "DateTime EEGGaming\&.Core\&.Data\&.Models\&.GamingSesion\&.Start\fR [get]\fP, \fR [set]\fP"

.PP
The time and date the gaming session start\&. 
.PP
Definition at line \fB27\fP of file \fBGamingSesion\&.cs\fP\&.
.SS "int EEGGaming\&.Core\&.Data\&.Models\&.GamingSesion\&.User\fR [get]\fP, \fR [set]\fP"

.PP
The user'sid that plays in the current session\&. 
.PP
Definition at line \fB38\fP of file \fBGamingSesion\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
