.TH "EEGGaming.Core.Data.NonDataModels" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Data.NonDataModels
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrainwaves\fP"
.br
.RI "The class representation of the packets containing the data coming from the headset\&. "
.ti -1c
.RI "class \fBGmingSessionViewModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
