.TH "EEGGaming.Core.Data.NonDataModels.GmingSessionViewModel" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Data.NonDataModels.GmingSessionViewModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEEGGaming\&.Core\&.Data\&.Models\&.GamingSesion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBImportToModel\fP (\fBGamingSesion\fP model)"
.br
.RI "Import the data of the GamingSession data model to theView Model\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUserName\fP\fR [get, set]\fP"
.br
.RI "Thename of the User\&. "
.in -1c

Properties inherited from \fBEEGGaming\&.Core\&.Data\&.Models\&.GamingSesion\fP
.in +1c
.ti -1c
.RI "int \fBId\fP\fR [get, set]\fP"
.br
.RI "An auto-incremented value id\&. "
.ti -1c
.RI "DateTime \fBStart\fP\fR [get, set]\fP"
.br
.RI "The time and date the gaming session start\&. "
.ti -1c
.RI "DateTime \fBEnd\fP\fR [get, set]\fP"
.br
.RI "The time and date the gaming session end\&. "
.ti -1c
.RI "int \fBUser\fP\fR [get, set]\fP"
.br
.RI "The user'sid that plays in the current session\&. "
.ti -1c
.RI "double \fBScore\fP\fR [get, set]\fP"
.br
.RI "The score the user scored in this gaming session\&. "
.in -1c
.SH "Detailed Description"
.PP 
The View Model representation of GamingSession table 
.PP
Definition at line \fB14\fP of file \fBGmingSessionViewModel\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void EEGGaming\&.Core\&.Data\&.NonDataModels\&.GmingSessionViewModel\&.ImportToModel (\fBGamingSesion\fP model)"

.PP
Import the data of the GamingSession data model to theView Model\&. 
.PP
\fBParameters\fP
.RS 4
\fImodel\fP data model with initial data
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBGmingSessionViewModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string EEGGaming\&.Core\&.Data\&.NonDataModels\&.GmingSessionViewModel\&.UserName\fR [get]\fP, \fR [set]\fP"

.PP
Thename of the User\&. 
.PP
Definition at line \fB21\fP of file \fBGmingSessionViewModel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
