.TH "EEGGaming.Core" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBData\fP"
.br
.ti -1c
.RI "namespace \fBManagers\fP"
.br
.ti -1c
.RI "namespace \fBMigrations\fP"
.br
.ti -1c
.RI "namespace \fBTools\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
