.TH "EEGGaming.Core/Data/EEGGamingDbContext.cs" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core/Data/EEGGamingDbContext.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEEGGaming\&.Core\&.Data\&.EEGGamingDbContext\fP"
.br
.RI "DbContext of the \fBEEGGaming\fP library\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEEGGaming\fP"
.br
.ti -1c
.RI "namespace \fBEEGGaming\&.Core\fP"
.br
.ti -1c
.RI "namespace \fBEEGGaming\&.Core\&.Data\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
