.TH "EEGGaming.Core.Tools" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Tools
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalculations\fP"
.br
.ti -1c
.RI "class \fBCommonTools\fP"
.br
.RI "Class with some common tools\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
