.TH "EEGGaming.Core.Tools.CommonTools" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Tools.CommonTools \- Class with some common tools\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCreateLogger\fP ()"
.br
.RI "Creates the Loger\&. "
.ti -1c
.RI "static Boolean \fBisEmpty\fP (string str)"
.br
.RI "Checks if a string is empty\&. "
.ti -1c
.RI "static void \fBErrorReporting\fP (Exception ex)"
.br
.RI "SavesErrors to log file\&. "
.ti -1c
.RI "static string \fBGetAppRootBinaryFolderAbsolutePath\fP ()"
.br
.RI "Gets the absolute path of the app's binary folder\&. "
.ti -1c
.RI "static string \fBGetAppRootDataFolderAbsolutePath\fP ()"
.br
.RI "gets the absolute path of app's data folder "
.ti -1c
.RI "static void \fBCreateAppRootdataFolder\fP ()"
.br
.RI "Createsthe app's data folder\&. "
.ti -1c
.RI "static string \fBGetEEGGamingCoreVersion\fP ()"
.br
.RI "Gets the version of \fBEEGGaming\fP \fBCore\fP\&. "
.ti -1c
.RI "static string \fBGetBlinkBirdbVersion\fP ()"
.br
.RI "Gets the version of Blinkbird\&. "
.ti -1c
.RI "static string \fBGetBlinkBirdDeveloper\fP ()"
.br
.RI "Gets the Developer of BlinkBird\&. "
.ti -1c
.RI "static string \fBGetBlinkBirdCopyright\fP ()"
.br
.RI "gwts the copyright of blinkbird "
.ti -1c
.RI "static string \fBGetEEGGamingCoreDeveloper\fP ()"
.br
.RI "Gets the developer of \fBEEGGaming\fP \fBCore\fP\&. "
.ti -1c
.RI "static string \fBGetEEGGamingCoreCopyright\fP ()"
.br
.RI "Gets the copyright of \fBEEGGaming\fP \fBCore\fP\&. "
.ti -1c
.RI "static string \fBGetEEGGamingCoreLastModifiedDateUTC\fP ()"
.br
.RI "Gets the date \fBEEGGaming\fP \fBCore\fP last modified 
.br
 "
.ti -1c
.RI "static string \fBGetBlickBirdbLastModifiedDateUTC\fP ()"
.br
.RI "Gets the date BlinkBird last modified\&. "
.ti -1c
.RI "static string \fBGetBlinBirdMD5Hash\fP ()"
.br
.RI "Gets the MDM5 Hash of Blinkbird\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Logger \fBlogger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class with some common tools\&. 
.PP
Definition at line \fB17\fP of file \fBCommonTools\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void EEGGaming\&.Core\&.Tools\&.CommonTools\&.CreateAppRootdataFolder ()\fR [static]\fP"

.PP
Createsthe app's data folder\&. 
.PP
Definition at line \fB181\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static void EEGGaming\&.Core\&.Tools\&.CommonTools\&.CreateLogger ()\fR [static]\fP"

.PP
Creates the Loger\&. 
.PP
Definition at line \fB23\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static void EEGGaming\&.Core\&.Tools\&.CommonTools\&.ErrorReporting (Exception ex)\fR [static]\fP"

.PP
SavesErrors to log file\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP error that occured
.RE
.PP

.PP
Definition at line \fB76\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetAppRootBinaryFolderAbsolutePath ()\fR [static]\fP"

.PP
Gets the absolute path of the app's binary folder\&. 
.PP
\fBReturns\fP
.RS 4
the absolute path of the app's binary folder
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetAppRootDataFolderAbsolutePath ()\fR [static]\fP"

.PP
gets the absolute path of app's data folder 
.PP
\fBReturns\fP
.RS 4
absolute path of app's data folder
.RE
.PP

.PP
Definition at line \fB142\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetBlickBirdbLastModifiedDateUTC ()\fR [static]\fP"

.PP
Gets the date BlinkBird last modified\&. 
.PP
\fBReturns\fP
.RS 4
date BlinkBird last modified
.RE
.PP

.PP
Definition at line \fB388\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetBlinBirdMD5Hash ()\fR [static]\fP"

.PP
Gets the MDM5 Hash of Blinkbird\&. 
.PP
\fBReturns\fP
.RS 4
Hash of Blinkbird 
.RE
.PP

.PP
Definition at line \fB411\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetBlinkBirdbVersion ()\fR [static]\fP"

.PP
Gets the version of Blinkbird\&. 
.PP
\fBReturns\fP
.RS 4
version of Blinkbird
.RE
.PP

.PP
Definition at line \fB228\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetBlinkBirdCopyright ()\fR [static]\fP"

.PP
gwts the copyright of blinkbird 
.PP
\fBReturns\fP
.RS 4
the copyright of blinkbird
.RE
.PP

.PP
Definition at line \fB281\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetBlinkBirdDeveloper ()\fR [static]\fP"

.PP
Gets the Developer of BlinkBird\&. 
.PP
\fBReturns\fP
.RS 4
Developer of BlinkBird
.RE
.PP

.PP
Definition at line \fB253\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetEEGGamingCoreCopyright ()\fR [static]\fP"

.PP
Gets the copyright of \fBEEGGaming\fP \fBCore\fP\&. 
.PP
\fBReturns\fP
.RS 4
copyright of \fBEEGGaming\fP \fBCore\fP 
.RE
.PP

.PP
Definition at line \fB338\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetEEGGamingCoreDeveloper ()\fR [static]\fP"

.PP
Gets the developer of \fBEEGGaming\fP \fBCore\fP\&. 
.PP
\fBReturns\fP
.RS 4
developer of \fBEEGGaming\fP \fBCore\fP 
.RE
.PP

.PP
Definition at line \fB310\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetEEGGamingCoreLastModifiedDateUTC ()\fR [static]\fP"

.PP
Gets the date \fBEEGGaming\fP \fBCore\fP last modified 
.br
 
.PP
\fBReturns\fP
.RS 4
date \fBEEGGaming\fP \fBCore\fP last modified 
.RE
.PP

.PP
Definition at line \fB366\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static string EEGGaming\&.Core\&.Tools\&.CommonTools\&.GetEEGGamingCoreVersion ()\fR [static]\fP"

.PP
Gets the version of \fBEEGGaming\fP \fBCore\fP\&. 
.PP
\fBReturns\fP
.RS 4
version of \fBEEGGaming\fP \fBCore\fP
.RE
.PP

.PP
Definition at line \fB207\fP of file \fBCommonTools\&.cs\fP\&.
.SS "static Boolean EEGGaming\&.Core\&.Tools\&.CommonTools\&.isEmpty (string str)\fR [static]\fP"

.PP
Checks if a string is empty\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to be checked 
.RE
.PP
\fBReturns\fP
.RS 4
true f its empty flase otherwise
.RE
.PP

.PP
Definition at line \fB53\fP of file \fBCommonTools\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Logger EEGGaming\&.Core\&.Tools\&.CommonTools\&.logger\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBCommonTools\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
