.TH "EEGGaming.Core.Migrations.ggggggg" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Migrations.ggggggg \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Migration\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUp\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBDown\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBBuildTargetModel\fP (ModelBuilder modelBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line \fB15\fP of file \fB20240831175225_ggggggg\&.Designer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void EEGGaming\&.Core\&.Migrations\&.ggggggg\&.BuildTargetModel (ModelBuilder modelBuilder)\fR [protected]\fP"

.PP

.PP
Definition at line \fB18\fP of file \fB20240831175225_ggggggg\&.Designer\&.cs\fP\&.
.SS "override void EEGGaming\&.Core\&.Migrations\&.ggggggg\&.Down (MigrationBuilder migrationBuilder)\fR [protected]\fP"

.PP

.PP
Definition at line \fB17\fP of file \fB20240831175225_ggggggg\&.cs\fP\&.
.SS "override void EEGGaming\&.Core\&.Migrations\&.ggggggg\&.Up (MigrationBuilder migrationBuilder)\fR [protected]\fP"

.PP

.PP
Definition at line \fB11\fP of file \fB20240831175225_ggggggg\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
