.TH "EEGGaming.Core.Data" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Data
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEEGGamingDbContext\fP"
.br
.RI "DbContext of the \fBEEGGaming\fP library\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
