.TH "EEGGaming.Core.Managers" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Managers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppSettingsManager\fP"
.br
.RI "This classmanages the settings of the library\&. "
.ti -1c
.RI "class \fBBaseManager\fP"
.br
.RI "The class that includes the mostly common methods,properties and fuctions of the Manager classes\&. "
.ti -1c
.RI "class \fBBrainWaveRecordManager\fP"
.br
.RI "The Manager that manages the records of the BrainWave table and detectsif an eye blink occured\&. "
.ti -1c
.RI "class \fBGamingSesionManager\fP"
.br
.ti -1c
.RI "class \fBUserManager\fP"
.br
.RI "Class that manages user's and their info\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBOnBlinked\fP ()"
.br
.RI "This event occurs when an eye blink occured\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate void EEGGaming\&.Core\&.Managers\&.OnBlinked ()"

.PP
This event occurs when an eye blink occured\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
