.TH "EEGGaming.Core.Migrations.chnagedtobrainwaveemodel" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Migrations.chnagedtobrainwaveemodel \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Migration\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUp\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBDown\fP (MigrationBuilder migrationBuilder)"
.br
.ti -1c
.RI "override void \fBBuildTargetModel\fP (ModelBuilder modelBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line \fB15\fP of file \fB20240607151943_chnagedtobrainwaveemodel\&.Designer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void EEGGaming\&.Core\&.Migrations\&.chnagedtobrainwaveemodel\&.BuildTargetModel (ModelBuilder modelBuilder)\fR [protected]\fP"

.PP

.PP
Definition at line \fB18\fP of file \fB20240607151943_chnagedtobrainwaveemodel\&.Designer\&.cs\fP\&.
.SS "override void EEGGaming\&.Core\&.Migrations\&.chnagedtobrainwaveemodel\&.Down (MigrationBuilder migrationBuilder)\fR [protected]\fP"

.PP

.PP
Definition at line \fB205\fP of file \fB20240607151943_chnagedtobrainwaveemodel\&.cs\fP\&.
.SS "override void EEGGaming\&.Core\&.Migrations\&.chnagedtobrainwaveemodel\&.Up (MigrationBuilder migrationBuilder)\fR [protected]\fP"

.PP

.PP
Definition at line \fB11\fP of file \fB20240607151943_chnagedtobrainwaveemodel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
