.TH "EEGGaming.Core.Data.Models.User" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Data.Models.User
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fR [get, set]\fP"
.br
.RI "An auto-incremented value id\&. "
.ti -1c
.RI "string \fBName\fP\fR [get, set]\fP"
.br
.RI "The name of the user\&. "
.ti -1c
.RI "string \fBSex\fP\fR [get, set]\fP"
.br
.RI "the sex of the user "
.ti -1c
.RI "int \fBAge\fP\fR [get, set]\fP"
.br
.RI "the age of the user "
.ti -1c
.RI "string \fBEducation\fP\fR [get, set]\fP"
.br
.RI "The education level of the user\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBUser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int EEGGaming\&.Core\&.Data\&.Models\&.User\&.Age\fR [get]\fP, \fR [set]\fP"

.PP
the age of the user 
.PP
Definition at line \fB37\fP of file \fBUser\&.cs\fP\&.
.SS "string EEGGaming\&.Core\&.Data\&.Models\&.User\&.Education\fR [get]\fP, \fR [set]\fP"

.PP
The education level of the user\&. 
.PP
Definition at line \fB42\fP of file \fBUser\&.cs\fP\&.
.SS "int EEGGaming\&.Core\&.Data\&.Models\&.User\&.Id\fR [get]\fP, \fR [set]\fP"

.PP
An auto-incremented value id\&. 
.PP
Definition at line \fB21\fP of file \fBUser\&.cs\fP\&.
.SS "string EEGGaming\&.Core\&.Data\&.Models\&.User\&.Name\fR [get]\fP, \fR [set]\fP"

.PP
The name of the user\&. 
.PP
Definition at line \fB27\fP of file \fBUser\&.cs\fP\&.
.SS "string EEGGaming\&.Core\&.Data\&.Models\&.User\&.Sex\fR [get]\fP, \fR [set]\fP"

.PP
the sex of the user 
.PP
Definition at line \fB32\fP of file \fBUser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
