.TH "GameOver" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameOver
.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBGameOver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void GameOver\&._Process (double delta)"

.PP
Definition at line \fB28\fP of file \fBGameOver\&.cs\fP\&.
.SS "override void GameOver\&._Ready ()"

.PP
Definition at line \fB8\fP of file \fBGameOver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
