.TH "GameOver" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameOver \- This window appearswhenn thegame is over\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.RI "It shows the score and saves the data to the database\&. "
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This window appearswhenn thegame is over\&. 
.PP
Definition at line \fB6\fP of file \fBGameOver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void GameOver\&._Process (double delta)"

.PP
Definition at line \fB32\fP of file \fBGameOver\&.cs\fP\&.
.SS "override void GameOver\&._Ready ()"

.PP
It shows the score and saves the data to the database\&. 
.PP
Definition at line \fB12\fP of file \fBGameOver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
