.TH "HSdrHorizontalSpeed" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSdrHorizontalSpeed \- This sldier controls the speed the scenec and the avatar moves\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits HSlider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.RI "moves the slider when the camera moves "
.in -1c
.SH "Detailed Description"
.PP 
This sldier controls the speed the scenec and the avatar moves\&. 
.PP
Definition at line \fB6\fP of file \fBHSdrHorizontalSpeed\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void HSdrHorizontalSpeed\&._Process (double delta)"

.PP
moves the slider when the camera moves 
.PP
\fBParameters\fP
.RS 4
\fIdelta\fP 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBHSdrHorizontalSpeed\&.cs\fP\&.
.SS "override void HSdrHorizontalSpeed\&._Ready ()"

.PP
Definition at line \fB10\fP of file \fBHSdrHorizontalSpeed\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
