.TH "BlinkBird/Code/HSdrHorizontalSpeed.cs" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlinkBird/Code/HSdrHorizontalSpeed.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHSdrHorizontalSpeed\fP"
.br
.RI "This sldier controls the speed the scenec and the avatar moves\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
