.TH "Mountain" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mountain \- The main obstacle of the avatar\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Sprite2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.RI "It checks whenver the avatar is in the area of the mounntain and after it kills the avatar it shows the gameover screen or it increases the score\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "PackedScene \fBpackedScene\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main obstacle of the avatar\&. 
.PP
Definition at line \fB7\fP of file \fBMountain\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Mountain\&._Process (double delta)"

.PP
It checks whenver the avatar is in the area of the mounntain and after it kills the avatar it shows the gameover screen or it increases the score\&. 
.PP
\fBParameters\fP
.RS 4
\fIdelta\fP 
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBMountain\&.cs\fP\&.
.SS "override void Mountain\&._Ready ()"

.PP
Definition at line \fB12\fP of file \fBMountain\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "PackedScene Mountain\&.packedScene\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB10\fP of file \fBMountain\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
