.TH "Mountain" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mountain
.SH SYNOPSIS
.br
.PP
.PP
Inherits Sprite2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "PackedScene \fBpackedScene\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBMountain\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Mountain\&._Process (double delta)"

.PP
Definition at line \fB19\fP of file \fBMountain\&.cs\fP\&.
.SS "override void Mountain\&._Ready ()"

.PP
Definition at line \fB10\fP of file \fBMountain\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "PackedScene Mountain\&.packedScene\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB8\fP of file \fBMountain\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
