.TH "BlinkBird/Code/Mountain.cs" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlinkBird/Code/Mountain.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMountain\fP"
.br
.RI "The main obstacle of the avatar\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
