.TH "EEGGaming.Trainer/Program.cs" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Trainer/Program.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEEGGaming\&.Trainer\&.Program\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBEEGGaming\fP"
.br
.ti -1c
.RI "namespace \fBEEGGaming\&.Trainer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
