.TH "ScoreandTime" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScoreandTime \- The Horizontal Split container that gorupss the scoreand the timer together\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits HSplitContainer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.RI "Checks if the camera moves and moves\&. "
.in -1c
.SH "Detailed Description"
.PP 
The Horizontal Split container that gorupss the scoreand the timer together\&. 
.PP
Definition at line \fB10\fP of file \fBScoreandTime\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ScoreandTime\&._Process (double delta)"

.PP
Checks if the camera moves and moves\&. 
.PP
\fBParameters\fP
.RS 4
\fIdelta\fP 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBScoreandTime\&.cs\fP\&.
.SS "override void ScoreandTime\&._Ready ()"

.PP
Definition at line \fB14\fP of file \fBScoreandTime\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
