.TH "BlinkBird/Code/ScoreandTime.cs" 3 "Version 0.2.8.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlinkBird/Code/ScoreandTime.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScoreandTime\fP"
.br
.RI "The Horizontal Split container that gorupss the scoreand the timer together\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
