.TH "World" 3 "Version 0.2.7.5" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World \- The class representation for the gaming world\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Node2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBRAISESCOREBY\fP = (float)(1)"
.br
.ti -1c
.RI "static double \fBScore\fP = 0"
.br
.ti -1c
.RI "static \fBGamingSesion\fP \fBgamingSesion\fP = new \fBGamingSesion\fP()"
.br
.ti -1c
.RI "static Timer \fBtimer\fP"
.br
.ti -1c
.RI "static \fBMountains\fP \fBMountains\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP"
.br
.ti -1c
.RI "static Label \fBspeedvalue\fP"
.br
.ti -1c
.RI "static HSlider \fBHslSpeed\fP"
.br
.ti -1c
.RI "static \fBCamera\fP \fBCamera\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The class representation for the gaming world\&. 
.PP
Definition at line \fB10\fP of file \fBWorld\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void World\&._Process (double delta)"

.PP
Definition at line \fB136\fP of file \fBWorld\&.cs\fP\&.
.SS "override void World\&._Ready ()"

.PP
Definition at line \fB38\fP of file \fBWorld\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCamera\fP World\&.Camera\fR [static]\fP"

.PP
Definition at line \fB26\fP of file \fBWorld\&.cs\fP\&.
.SS "\fBGamingSesion\fP World\&.gamingSesion = new \fBGamingSesion\fP()\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBWorld\&.cs\fP\&.
.SS "HSlider World\&.HslSpeed\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBWorld\&.cs\fP\&.
.SS "\fBMountains\fP World\&.Mountains\fR [static]\fP"

.PP
Definition at line \fB21\fP of file \fBWorld\&.cs\fP\&.
.SS "\fBPlayer\fP World\&.player\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBWorld\&.cs\fP\&.
.SS "const float World\&.RAISESCOREBY = (float)(1)\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBWorld\&.cs\fP\&.
.SS "double World\&.Score = 0\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBWorld\&.cs\fP\&.
.SS "Label World\&.speedvalue\fR [static]\fP"

.PP
Definition at line \fB24\fP of file \fBWorld\&.cs\fP\&.
.SS "Timer World\&.timer\fR [static]\fP"

.PP
Definition at line \fB20\fP of file \fBWorld\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
