.TH "AddUserDetails" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddUserDetails
.SH SYNOPSIS
.br
.PP
.PP
Inherits Control\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBAddUserDetails\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void AddUserDetails\&._Process (double delta)"

.PP
Definition at line \fB47\fP of file \fBAddUserDetails\&.cs\fP\&.
.SS "override void AddUserDetails\&._Ready ()"

.PP
Definition at line \fB10\fP of file \fBAddUserDetails\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
