.TH "EEGGaming.Core.Migrations" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEGGaming.Core.Migrations
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaddedscoreongamingsession\fP"
.br
.ti -1c
.RI "class \fBaddedusername\fP"
.br
.ti -1c
.RI "class \fBchangedscoretype\fP"
.br
.ti -1c
.RI "class \fBchangesoretype\fP"
.br
.ti -1c
.RI "class \fBchnagedtobrainwaveemodel\fP"
.br
.ti -1c
.RI "class \fBdddddddd\fP"
.br
.ti -1c
.RI "class \fBEEGGamingDbContextModelSnapshot\fP"
.br
.ti -1c
.RI "class \fBfff\fP"
.br
.ti -1c
.RI "class \fBggggggg\fP"
.br
.ti -1c
.RI "class \fBinitailcreation\fP"
.br
.ti -1c
.RI "class \fBinitial\fP"
.br
.ti -1c
.RI "class \fBmadethenamepropertyakey\fP"
.br
.ti -1c
.RI "class \fBremovedmode\fP"
.br
.ti -1c
.RI "class \fBunmadethenamepropertyakey\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
