.TH "GamingScesions" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GamingScesions
.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBGamingScesions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void GamingScesions\&._Process (double delta)"

.PP
Definition at line \fB141\fP of file \fBGamingScesions\&.cs\fP\&.
.SS "override void GamingScesions\&._Ready ()"

.PP
Definition at line \fB20\fP of file \fBGamingScesions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
