.TH "Menu" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu
.SH SYNOPSIS
.br
.PP
.PP
Inherits Control\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.ti -1c
.RI "void \fBbbtnNewGame_pressed\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSaveDataToDb\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBBrainWaveRecordManager\fP \fBrecordManager\fP = new \fBBrainWaveRecordManager\fP()"
.br
.ti -1c
.RI "static \fBGamingSesionManager\fP \fBgamingSesionManager\fP = new \fBGamingSesionManager\fP()"
.br
.ti -1c
.RI "static \fBUserManager\fP \fBuserManager\fP = new \fBUserManager\fP()"
.br
.ti -1c
.RI "static \fBUser\fP \fBSelectedUser\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBMenu\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Menu\&._Process (double delta)"

.PP
Definition at line \fB140\fP of file \fBMenu\&.cs\fP\&.
.SS "override void Menu\&._Ready ()"

.PP
Definition at line \fB27\fP of file \fBMenu\&.cs\fP\&.
.SS "void Menu\&.bbtnNewGame_pressed ()"

.PP
Definition at line \fB155\fP of file \fBMenu\&.cs\fP\&.
.SS "static void Menu\&.SaveDataToDb ()\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBMenu\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGamingSesionManager\fP Menu\&.gamingSesionManager = new \fBGamingSesionManager\fP()\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBMenu\&.cs\fP\&.
.SS "\fBBrainWaveRecordManager\fP Menu\&.recordManager = new \fBBrainWaveRecordManager\fP()\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBMenu\&.cs\fP\&.
.SS "\fBUser\fP Menu\&.SelectedUser = null\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBMenu\&.cs\fP\&.
.SS "\fBUserManager\fP Menu\&.userManager = new \fBUserManager\fP()\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBMenu\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
