.TH "Mountains" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mountains
.SH SYNOPSIS
.br
.PP
.PP
Inherits Node2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBMountains\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Mountains\&._Process (double delta)"

.PP
Definition at line \fB13\fP of file \fBMountains\&.cs\fP\&.
.SS "override void Mountains\&._Ready ()"

.PP
Definition at line \fB7\fP of file \fBMountains\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
