.TH "Player" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player
.SH SYNOPSIS
.br
.PP
.PP
Inherits Sprite2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBYMOVEMENT\fP = (0\&.025f)*16"
.br
.ti -1c
.RI "const float \fBXMOVEMENT\fP = (0\&.025f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPlayer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Player\&._Process (double delta)"
14832
.PP
Definition at line \fB22\fP of file \fBPlayer\&.cs\fP\&.
.SS "override void Player\&._Ready ()"

.PP
Definition at line \fB14\fP of file \fBPlayer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const float Player\&.XMOVEMENT = (0\&.025f)\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBPlayer\&.cs\fP\&.
.SS "const float Player\&.YMOVEMENT = (0\&.025f)*16\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBPlayer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
