.TH "Sky" 3 "Version 0.2.6.0" "EEGGaming And Blinkbird" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sky
.SH SYNOPSIS
.br
.PP
.PP
Inherits Sprite2D\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_Ready\fP ()"
.br
.ti -1c
.RI "override void \fB_Process\fP (double delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSky\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Sky\&._Process (double delta)"

.PP
Definition at line \fB13\fP of file \fBSky\&.cs\fP\&.
.SS "override void Sky\&._Ready ()"

.PP
Definition at line \fB7\fP of file \fBSky\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EEGGaming And Blinkbird from the source code\&.
